# Generated by Django 3.1.6 on 2021-10-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Components', models.TextField(blank=True, verbose_name='Состав')),
                ('BuildTime', models.CharField(max_length=50, verbose_name='Время сборки')),
                ('About', models.TextField(blank=True, verbose_name='Описание')),
                ('Price', models.IntegerField(verbose_name='Цена')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Цветы',
                'verbose_name_plural': 'Цветы',
            },
        ),
    ]
