# Generated by Django 3.1.6 on 2021-10-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_flowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='Image',
            field=models.ImageField(default=123, upload_to='flowers/', verbose_name='Постер'),
            preserve_default=False,
        ),
    ]
