# Generated by Django 3.1.6 on 2021-10-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flowers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=120)),
                ('сategory_id', models.CharField(max_length=120)),
                ('product_id', models.CharField(max_length=120)),
                ('product_value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Корзина пользователя (системное)',
                'verbose_name_plural': 'Корзина пользователя (системное)',
            },
        ),
    ]
