# Generated by Django 3.1.6 on 2021-10-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(upload_to='category/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='Image',
            field=models.ImageField(upload_to='flowers/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.flowers', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Популярное',
                'verbose_name_plural': 'Популярное',
            },
        ),
    ]
