# Generated by Django 3.1.6 on 2021-10-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20211021_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='Additionally',
            field=models.CharField(blank=True, choices=[('Популярно', 'Популярно')], max_length=50, verbose_name='Дополнительно'),
        ),
        migrations.DeleteModel(
            name='Popular',
        ),
    ]
