# Generated by Django 3.1.6 on 2021-10-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='FIO',
        ),
        migrations.AddField(
            model_name='order',
            name='Name',
            field=models.CharField(default=0, max_length=120, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
