# Generated by Django 4.0.1 on 2022-01-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ShowInMenu',
            field=models.CharField(choices=[('Не отображать', 'Не отображать'), ('Отображать', 'Отображать')], default=1, max_length=50, verbose_name='Отображение в меню'),
            preserve_default=False,
        ),
    ]
