# Generated by Django 4.0.1 on 2022-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePaymentTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=120)),
                ('Session_key', models.CharField(max_length=120)),
                ('Status', models.CharField(choices=[('Оплачено', 'Оплачено'), ('Не оплачено', 'Не оплачено')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Обрабатывается', 'Обрабатывается'), ('Доставляется', 'Доставляется'), ('Готово к выдаче', 'Готово к выдаче'), ('Выдано', 'Выдано'), ('Оплачен', 'Оплачен')], max_length=50, verbose_name='Статус заказа'),
        ),
    ]
