# Generated by Django 4.0.1 on 2022-02-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_onlinepaymenttemp_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepaymenttemp',
            name='Email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinepaymenttemp',
            name='FullPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinepaymenttemp',
            name='Name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinepaymenttemp',
            name='Phone',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
